version: 2.9.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    msbuild .\Source\Svg.sln /p:configuration=Release

    nuget pack .\Source\Svg.csproj -properties Configuration=Release
artifacts:
- path: Svg.*.nupkg
  name: PackageFile
deploy:
- provider: NuGet
  server: https://artifactory.articulate.com/artifactory/api/nuget/nuget-local
  api_key:
    secure: F5AJkry9VKS7NNyidtyaFt1Oomgk324GVOfheoS9ZxQ=
  skip_symbols: true
  artifact: PackageFile
  on:
    branch: master