version: 3.1.1.{build}
image: Visual Studio 2019
pull_requests:
  do_not_increment_build_number: true
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    nuget restore .\Source\Svg.sln

    msbuild .\Source\Svg.sln /p:configuration=Release
artifacts:
- path: .\Source\bin\release\Articulate.Svg.*.nupkg
  name: PackageFile
deploy:
- provider: NuGet
  server: https://artifactory.articulate.com/artifactory/api/nuget/nuget-local
  api_key:
    secure: F5AJkry9VKS7NNyidtyaFt1Oomgk324GVOfheoS9ZxQ=
  skip_symbols: true
  artifact: PackageFile
  on:
    branch: master