version: 2.9.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
artifacts:
- path: Svg.*.nupkg
  name: PackageFile
deploy:
- provider: NuGet
  server: https://artifactory.articulate.com/artifactory/api/nuget/nuget-local
  api_key:
    secure: F5AJkry9VKS7NNyidtyaFt1Oomgk324GVOfheoS9ZxQ=
  artifact: PackageFile
  on:
    branch: master