version: 3.1.1.{build}
image: Visual Studio 2019
pull_requests:
  do_not_increment_build_number: true
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    nuget restore .\Source\Svg.sln

    msbuild .\Source\Svg.sln /p:configuration=Release
artifacts:
- path: '**\Articulate.Svg.*.nupkg'
  name: PackageFile
deploy:
- provider: NuGet
  server: https://artifactory.articulate.com/artifactory/api/nuget/nuget-local
  api_key:
    secure: I2fPs5m1kSHTtbHd03Lu+cM8KGP97xPnopLZ6OVhoLMRWfVy/cEcVp0BKYB3bf3gT/Zp1qp3tRfFfpAvwy6jNcmY6pI3Y1fWoKd6BVyutj1kz+3BQVkbU3CKTh5VyyvO6OZBS/MSlqSs8c7SVaqZwiMaDOUwAKU23gKjnGKpKCc=
  skip_symbols: true
  artifact: PackageFile
  on:
    branch: master